name: CI

on:
  workflow_dispatch:
    inputs:
      docker-question:
        description: 'Do you want to build and push the docker image?'
        required: true
        type: string
        default: 'no'

env:
  AWS_REGION: 'eu-west-2'

jobs:
  aws-configure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: test pipeline, print AWS region
        run: 'echo AWS region is $AWS_REGION'

      - name: login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 313196412030.dkr.ecr.eu-west-2.amazonaws.com

      - name: build docker image
        run: echo "hello world"
